"""Compatibility imports for provider configuration, discovery, and requests.

The implementations live in provider_registry, provider_discovery, and
provider_requests. Existing callers also import private helpers here.
"""
from __future__ import annotations

from provider_registry import (
    copy,
    datetime,
    timezone,
    hashlib,
    ipaddress,
    json,
    math,
    re,
    ssl,
    urllib,
    ProviderError,
    repair_openai_tool_order,
    GATEWAY_USER_AGENT,
    PROVIDERS,
    QWEN_DESCRIPTOR,
    QWEN_PATHS,
    QwenError,
    qwen_catalogue,
    qwen_controls,
    OPENROUTER_DESCRIPTOR,
    OPENROUTER_PATHS,
    OpenRouterError,
    openrouter_discover,
    openrouter_finalize,
    openrouter_controls,
    openrouter_app_headers,
    GEMINI_DESCRIPTOR,
    GEMINI_PATHS,
    GeminiError,
    gemini_discover,
    gemini_prepare_request,
    gemini_validate_connection,
    DEVIN_DESCRIPTOR,
    DEVIN_PATHS,
    DevinAgentError,
    devin_catalogue,
    devin_validate_connection,
    EFFORT_ORDER,
    CEREBRAS_EFFORT_ALIASES,
    DEEPSEEK_EFFORT_ALIASES,
    MISTRAL_EFFORT_ALIASES,
    MISTRAL_REASONING_EFFORTS,
    cap_high_end,
    map_effort,
    mistral_effort_modes,
    nearest_effort,
    ollama_effort_aliases,
    ollama_effort_modes,
    _OFFICIAL_PATHS,
    _OLLAMA_PATHS,
    _MODEL_ID,
    _FUNCTION_NAME,
    _LOCAL_CREDENTIAL_FIELDS,
    FILE_EDIT_TOOLS,
    FILE_TOOL_STEERING,
    _needs_file_tool_steering,
    _KIMI_DOCS,
    _KIMI_FIXED_THINKING_MODELS,
    _KIMI_MODELS,
    _MIMO_DOCS,
    _MIMO_MODELS,
    _DEEPSEEK_DOCS,
    _OLLAMA_PUBLISHED_CONTEXT,
    _published_ollama_context,
    _DEEPSEEK_MODEL_METADATA,
    _MUSE_COOKBOOK,
    _MUSE_REASONING_DOCS,
    _MUSE_EFFORT_RANKS,
    _GROK_MODEL_DOCS,
    _GROK_REASONING_DOCS,
    _GROK_MODEL_METADATA,
    _CLAUDE_CONTEXT_DOCS,
    _CLAUDE_CONTEXT_WINDOWS,
    documented_context,
    _MUSE_MODEL_METADATA,
    _MUSE_NON_CHAT_MODELS,
    _CEREBRAS_PUBLIC_DOCS,
    _CEREBRAS_PUBLIC_MODELS_URL,
    _CEREBRAS_MODEL_METADATA,
    provider_defaults,
    _provider,
    _split_url,
    _validate_ollama_base,
    _official_base,
    validate_connection,
    _auth_headers,
)
from provider_discovery import (
    _NoRedirect,
    _fetch_json,
    _now_iso,
    _catalogue_entry,
    _static_catalogue,
    _discovery_plan,
    _ollama_show_plan,
    _cerebras_public_plan,
    _positive_integer,
    _boolean,
    _first_positive,
    _merge_objects,
    _ollama_declared_context,
    _ollama_models,
    _cerebras_entry,
    _grok_entry,
    _muse_entry,
    _coalesce_mistral_models,
    _models_from_api,
    _CODEX_CHAT_MODEL,
    discover as _discover,
)
from provider_requests import (
    _valid_model_id,
    _content_blocks,
    _append_system_value,
    _output_effort,
    _write_output_effort,
    _thinking_type,
    _muse_effort,
    _write_thinking_type,
    _normalize_native_controls,
    _normalize_native_payload,
    _contains_content_type,
    _estimated_input_tokens,
    _image_input_rejected,
    _image_capability_error,
    _apply_native_model_limits,
    _chat_name,
    _chat_tool_id,
    _requires_cerebras_replay,
    _chat_content_part,
    _compact_chat_content,
    _chat_effort,
    _reasoning_map,
    _translate_chat_payload,
    prepare_request,
)


def discover(provider_id: str, connection: dict | None, api_key: str | None, *, transport=None) -> dict:
    """Discover models while preserving the legacy metadata transport hook."""
    return _discover(provider_id, connection, api_key, transport=transport or _fetch_json)
